server:
  port: 8080
  servlet:
      context-path: /identity

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/identity_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
